import React from "react";
import Head from "next/head";
import DashboardLayout from "../../../layout/dashboardLayout/DashboardLayout";
import ArtistComponent from "../../../components/ArtistComponent";
import { useRouter } from "next/dist/client/router";
import ArtistForm from "../../../components/forms/ArtistForm";

export default function Pages() {
    const router = useRouter();

    return (
        <div>
            <Head>
                <title>Artist</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <DashboardLayout>
                    {router.asPath.includes("VIEW-ARTIST") && <ArtistComponent />}
                    {(router.asPath.includes("ADD-ARTIST") || router.asPath.includes("UPDATE-ARTIST")) && (
                        <ArtistForm />
                    )}
                </DashboardLayout>
            </main>
        </div>
    );
}
