import React from "react";
import Head from "next/head";
import DashboardLayout from "../../layout/dashboardLayout/DashboardLayout";
import AlertMessage from "../../utils/AlertMessage/AlertMessage";

export default function DashboardHome() {
    return (
        <div>
            <Head>
                <title>My Beats Dasdboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <DashboardLayout></DashboardLayout>
            </main>
        </div>
    );
}
